# Generated by Django 4.0.1 on 2022-02-16 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
